spring:
  application:
    name: Iservice
  datasource:
    # TODO: replace db setting with environment variables
    url: jdbc:postgresql://localhost:5432/Iservice
    username: postgres
    password: 14273119
  jpa:
    hibernate:
      ddl-auto: none
  spring-doc:
    pathsToMatch:
      - /auth/**
      - /api/v1/**
    swagger-ui:
      use-root-path: true
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
